In [0]:

import tensorflow

In [0]:
import keras

In [0]:



import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:

dataset = pd.read_csv('Churn_Modelling.csv')
X= dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

# New Section

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [0]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [80]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

TypeError: ignored

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [84]:
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=10))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=10, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
classifier=Sequential()

In [86]:
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [87]:
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [89]:
classifier.fit(X_train,y_train, batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 2s 249us/step - loss: 0.5022 - accuracy: 0.7951
Epoch 2/100
8000/8000 [==============================] - 2s 241us/step - loss: 0.4226 - accuracy: 0.8148
Epoch 3/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.4110 - accuracy: 0.8227
Epoch 4/100
8000/8000 [==============================] - 2s 240us/step - loss: 0.4032 - accuracy: 0.8251
Epoch 5/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.3975 - accuracy: 0.8267
Epoch 6/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.3928 - accuracy: 0.8284
Epoch 7/100
8000/8000 [==============================] - 2s 255us/step - loss: 0.3894 - accuracy: 0.8276
Epoch 8/100
8000/8000 [==============================] - 2s 257us/step - loss: 0.3866 - accuracy: 0.8285
Epoch 9/100
8000/8000 [==============================] - 2s 256us/step - loss: 0.3841 - accuracy: 0.8294
Epoch 10/100
8000/8000 [==============================]

In [0]:
y_pred = classifier.predict(X_test)

In [91]:
y_pred

array([[0.17429805],
       [0.40966034],
       [0.20532936],
       ...,
       [0.08428591],
       [0.09876032],
       [0.23541868]], dtype=float32)

In [0]:
y_pred=(y_pred > 0.5)

In [93]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [94]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1534   61]
 [ 211  194]]


In [95]:
(1475+234)/2000

0.8545